class DeuRuimError(Exception):
    pass


def testar():
    raise DeuRuimError('VocÃª conseguiu')


try:
    testar()
except DeuRuimError as err:
    print(f'Deu ruim: {err}')
